# -*- coding: utf-8 -*-
"""BC3415 Wk 11 Homework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsPbu_rbWi27dFGU9x4ybR_jYpNxrM-4
"""
from flask import Flask,request,render_template
import google.generativeai as palm
import replicate
import os
import time

api = os.getenv("MAKERSUITE_API_TOKEN")

palm.configure(api_key=api)
model = {
    "model": "models/chat-bison-001",
}

name=""
flag=1

app = Flask(__name__)

@app.route("/",methods=["GET","POST"])
def index():
    global flag
    flag=1
    return(render_template("index.html"))

@app.route("/main",methods=["GET","POST"])
def main():
    global flag,name
    if flag==1:
        name = request.form.get("name")
        flag=0
    return(render_template("main.html",r=name))

@app.route("/request_palm",methods=["GET","POST"])
def palm_request():
    return(render_template("request_palm.html"))

@app.route("/reply_palm",methods=["GET","POST"])
def palm_reply():
    q = request.form.get("q")
    r = palm.chat(
        **model,
        messages=q
    )
    return(render_template("reply_palm.html",r=r.last))

@app.route("/request_image",methods=["GET","POST"])
def image_request():
    return(render_template("request_image.html"))

@app.route("/reply_image",methods=["GET","POST"])
def image_reply():
    q = request.form.get("q")
    r = replicate.run(
        "ai-forever/kandinsky-2.2:ea1addaab376f4dc227f5368bbd8eff901820fd1cc14ed8cad63b29249e9d463",
        input={
            "prompt": q,
        },
    )
    return(render_template("reply_image.html",r=r[0]))

@app.route("/request_music",methods=["GET","POST"])
def music_request():
    return(render_template("request_music.html"))

@app.route("/reply_music",methods=["GET","POST"])
def music_reply():
    q = request.form.get("q")
    r = replicate.run(
        "suno-ai/bark:b76242b40d67c76ab6742e987628a2a9ac019e11d56ab96c4e91ce03b79b2787",
        input={
            "prompt": q,
            "duration:": 5
        }
    )
    return(render_template("reply_music.html",r=r))

@app.route("/request_video",methods=["GET","POST"])
def video_request():
    return(render_template("request_video.html"))

@app.route("/reply_video",methods=["GET","POST"])
def video_reply():
    q = request.form.get("q")
    r = replicate.run(
        "lucataco/animate-diff:beecf59c4aee8d81bf04f0381033dfa10dc16e845b4ae00d281e2fa377e48a9f",
        input={
            "prompt": q,
            "num_frames": 5
        }
    )
    time.sleep(60)
    return(render_template("reply_video.html",r=r[0]))

if __name__ == "__main__":
    app.run()
