# -*- coding: utf-8 -*-
"""BC3415 Wk 11 Homework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsPbu_rbWi27dFGU9x4ybR_jYpNxrM-4
"""
from flask import Flask,request,render_template
import google.generativeai as palm
import replicate
import os
import time

api = os.getenv("MAKERSUITE_API_TOKEN")

palm.configure(api_key=api)
model = {
    "model": "models/chat-bison-001",
}

name=""
flag=1

app = Flask(__name__)

@app.route("/",methods=["GET","POST"])
def index():
    global flag
    flag=1
    return(render_template("index.html"))

@app.route("/main",methods=["GET","POST"])
def main():
    global flag,name
    if flag==1:
        name = request.form.get("name")
        flag=0
    return(render_template("main.html",r=name))

@app.route("/request_palm",methods=["GET","POST"])
def palm_request():
    return(render_template("request_palm.html"))

@app.route("/reply_palm",methods=["GET","POST"])
def palm_reply():
    q = request.form.get("q")
    r = palm.chat(
        **model,
        messages=q
    )
    return(render_template("reply_palm.html",r=r.last))

@app.route("/request_image",methods=["GET","POST"])
def image_request():
    return(render_template("request_image.html"))

@app.route("/reply_image",methods=["GET","POST"])
def image_reply():
    q = request.form.get("q")
    r = replicate.run(
        "stability-ai/stable-diffusion:db21e45d3f7023abc2a46ee38a23973f6dce16bb082a930b0c49861f96d1e5bf",
        input={
            "prompt": q,
        },
    )
    return(render_template("reply_image.html",r=r[0]))

@app.route("/request_music",methods=["GET","POST"])
def music_request():
    return(render_template("request_music.html"))

@app.route("/reply_music",methods=["GET","POST"])
def music_reply():
    q = request.form.get("q")
    r = replicate.run(
        "meta/musicgen:7be0f12c54a8d033a0fbd14418c9af98962da9a86f5ff7811f9b3423a1f0b7d7",
        input={
            "prompt": q,
            "duration:": 5
        }
    )
    return(render_template("reply_music.html",r=r))

@app.route("/request_video",methods=["GET","POST"])
def video_request():
    return(render_template("request_video.html"))

@app.route("/reply_video",methods=["GET","POST"])
def video_reply():
    q = request.form.get("q")
    r = replicate.run(
        "anotherjesse/zeroscope-v2-xl:9f747673945c62801b13b84701c783929c0ee784e4748ec062204894dda1a351",
        input={
            "prompt": q,
            "num_frames": 5
        }
    )
    time.sleep(60)
    return(render_template("reply_video.html",r=r[0]))

if __name__ == "__main__":
    app.run()
